/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as MercadoImobiliarioRouteImport } from './routes/mercado-imobiliario'
import { Route as MeioAmbienteRouteImport } from './routes/meio-ambiente'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GuiaTamboreRouteImport } from './routes/guia-tambore'
import { Route as GuiaSantanaDeParnaibaRouteImport } from './routes/guia-santana-de-parnaiba'
import { Route as GuiaBarueriRouteImport } from './routes/guia-barueri'
import { Route as GuiaAlphavilleRouteImport } from './routes/guia-alphaville'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlphavilleRouteImport } from './routes/alphaville'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeioAmbienteIndexRouteImport } from './routes/meio-ambiente.index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as GuiaIndexRouteImport } from './routes/guia.index'
import { Route as CondominiosIndexRouteImport } from './routes/condominios.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BairrosIndexRouteImport } from './routes/bairros.index'
import { Route as MeioAmbienteLazerRouteImport } from './routes/meio-ambiente.lazer'
import { Route as MeioAmbienteFaunaRouteImport } from './routes/meio-ambiente.fauna'
import { Route as MeioAmbienteAreasRouteImport } from './routes/meio-ambiente.areas'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'
import { Route as GuiaSlugRouteImport } from './routes/guia.$slug'
import { Route as CondominiosSlugRouteImport } from './routes/condominios.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BairrosSlugRouteImport } from './routes/bairros.$slug'
import { Route as ArtigosSlugRouteImport } from './routes/artigos.$slug'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCmsIndexRouteImport } from './routes/_authenticated/cms.index'
import { Route as AuthenticatedCmsIdRouteImport } from './routes/_authenticated/cms.$id'
import { Route as AuthenticatedAuditIdRouteImport } from './routes/_authenticated/audit.$id'
import { Route as ApiPublicEditorialImageSplatRouteImport } from './routes/api/public/editorial-image.$'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoImobiliarioRoute = MercadoImobiliarioRouteImport.update({
  id: '/mercado-imobiliario',
  path: '/mercado-imobiliario',
  getParentRoute: () => rootRouteImport,
} as any)
const MeioAmbienteRoute = MeioAmbienteRouteImport.update({
  id: '/meio-ambiente',
  path: '/meio-ambiente',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaTamboreRoute = GuiaTamboreRouteImport.update({
  id: '/guia-tambore',
  path: '/guia-tambore',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaSantanaDeParnaibaRoute = GuiaSantanaDeParnaibaRouteImport.update({
  id: '/guia-santana-de-parnaiba',
  path: '/guia-santana-de-parnaiba',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaBarueriRoute = GuiaBarueriRouteImport.update({
  id: '/guia-barueri',
  path: '/guia-barueri',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaAlphavilleRoute = GuiaAlphavilleRouteImport.update({
  id: '/guia-alphaville',
  path: '/guia-alphaville',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphavilleRoute = AlphavilleRouteImport.update({
  id: '/alphaville',
  path: '/alphaville',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeioAmbienteIndexRoute = MeioAmbienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeioAmbienteRoute,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImoveisRoute,
} as any)
const GuiaIndexRoute = GuiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuiaRoute,
} as any)
const CondominiosIndexRoute = CondominiosIndexRouteImport.update({
  id: '/condominios/',
  path: '/condominios/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BairrosIndexRoute = BairrosIndexRouteImport.update({
  id: '/bairros/',
  path: '/bairros/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeioAmbienteLazerRoute = MeioAmbienteLazerRouteImport.update({
  id: '/lazer',
  path: '/lazer',
  getParentRoute: () => MeioAmbienteRoute,
} as any)
const MeioAmbienteFaunaRoute = MeioAmbienteFaunaRouteImport.update({
  id: '/fauna',
  path: '/fauna',
  getParentRoute: () => MeioAmbienteRoute,
} as any)
const MeioAmbienteAreasRoute = MeioAmbienteAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => MeioAmbienteRoute,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ImoveisRoute,
} as any)
const GuiaSlugRoute = GuiaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuiaRoute,
} as any)
const CondominiosSlugRoute = CondominiosSlugRouteImport.update({
  id: '/condominios/$slug',
  path: '/condominios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BairrosSlugRoute = BairrosSlugRouteImport.update({
  id: '/bairros/$slug',
  path: '/bairros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosSlugRoute = ArtigosSlugRouteImport.update({
  id: '/artigos/$slug',
  path: '/artigos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsIndexRoute = AuthenticatedCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedCmsIdRoute = AuthenticatedCmsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedAuditIdRoute = AuthenticatedAuditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAuditRoute,
} as any)
const ApiPublicEditorialImageSplatRoute =
  ApiPublicEditorialImageSplatRouteImport.update({
    id: '/api/public/editorial-image/$',
    path: '/api/public/editorial-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alphaville': typeof AlphavilleRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia': typeof GuiaRouteWithChildren
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/investimentos': typeof InvestimentosRoute
  '/meio-ambiente': typeof MeioAmbienteRouteWithChildren
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/cms': typeof AuthenticatedCmsRouteWithChildren
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/meio-ambiente/areas': typeof MeioAmbienteAreasRoute
  '/meio-ambiente/fauna': typeof MeioAmbienteFaunaRoute
  '/meio-ambiente/lazer': typeof MeioAmbienteLazerRoute
  '/bairros/': typeof BairrosIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/condominios/': typeof CondominiosIndexRoute
  '/guia/': typeof GuiaIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/meio-ambiente/': typeof MeioAmbienteIndexRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
  '/cms/$id': typeof AuthenticatedCmsIdRoute
  '/cms/': typeof AuthenticatedCmsIndexRoute
  '/api/public/editorial-image/$': typeof ApiPublicEditorialImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alphaville': typeof AlphavilleRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/investimentos': typeof InvestimentosRoute
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/meio-ambiente/areas': typeof MeioAmbienteAreasRoute
  '/meio-ambiente/fauna': typeof MeioAmbienteFaunaRoute
  '/meio-ambiente/lazer': typeof MeioAmbienteLazerRoute
  '/bairros': typeof BairrosIndexRoute
  '/blog': typeof BlogIndexRoute
  '/condominios': typeof CondominiosIndexRoute
  '/guia': typeof GuiaIndexRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/meio-ambiente': typeof MeioAmbienteIndexRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
  '/cms/$id': typeof AuthenticatedCmsIdRoute
  '/cms': typeof AuthenticatedCmsIndexRoute
  '/api/public/editorial-image/$': typeof ApiPublicEditorialImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alphaville': typeof AlphavilleRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia': typeof GuiaRouteWithChildren
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/investimentos': typeof InvestimentosRoute
  '/meio-ambiente': typeof MeioAmbienteRouteWithChildren
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRouteWithChildren
  '/_authenticated/cms': typeof AuthenticatedCmsRouteWithChildren
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/meio-ambiente/areas': typeof MeioAmbienteAreasRoute
  '/meio-ambiente/fauna': typeof MeioAmbienteFaunaRoute
  '/meio-ambiente/lazer': typeof MeioAmbienteLazerRoute
  '/bairros/': typeof BairrosIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/condominios/': typeof CondominiosIndexRoute
  '/guia/': typeof GuiaIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/meio-ambiente/': typeof MeioAmbienteIndexRoute
  '/_authenticated/audit/$id': typeof AuthenticatedAuditIdRoute
  '/_authenticated/cms/$id': typeof AuthenticatedCmsIdRoute
  '/_authenticated/cms/': typeof AuthenticatedCmsIndexRoute
  '/api/public/editorial-image/$': typeof ApiPublicEditorialImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alphaville'
    | '/auth'
    | '/blog'
    | '/empresas'
    | '/escolas'
    | '/guia'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/imoveis'
    | '/investimentos'
    | '/meio-ambiente'
    | '/mercado-imobiliario'
    | '/restaurantes'
    | '/sitemap.xml'
    | '/admin'
    | '/audit'
    | '/cms'
    | '/artigos/$slug'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominios/$slug'
    | '/guia/$slug'
    | '/imoveis/$slug'
    | '/meio-ambiente/areas'
    | '/meio-ambiente/fauna'
    | '/meio-ambiente/lazer'
    | '/bairros/'
    | '/blog/'
    | '/condominios/'
    | '/guia/'
    | '/imoveis/'
    | '/meio-ambiente/'
    | '/audit/$id'
    | '/cms/$id'
    | '/cms/'
    | '/api/public/editorial-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alphaville'
    | '/auth'
    | '/empresas'
    | '/escolas'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/investimentos'
    | '/mercado-imobiliario'
    | '/restaurantes'
    | '/sitemap.xml'
    | '/admin'
    | '/audit'
    | '/artigos/$slug'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominios/$slug'
    | '/guia/$slug'
    | '/imoveis/$slug'
    | '/meio-ambiente/areas'
    | '/meio-ambiente/fauna'
    | '/meio-ambiente/lazer'
    | '/bairros'
    | '/blog'
    | '/condominios'
    | '/guia'
    | '/imoveis'
    | '/meio-ambiente'
    | '/audit/$id'
    | '/cms/$id'
    | '/cms'
    | '/api/public/editorial-image/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alphaville'
    | '/auth'
    | '/blog'
    | '/empresas'
    | '/escolas'
    | '/guia'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/imoveis'
    | '/investimentos'
    | '/meio-ambiente'
    | '/mercado-imobiliario'
    | '/restaurantes'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/audit'
    | '/_authenticated/cms'
    | '/artigos/$slug'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominios/$slug'
    | '/guia/$slug'
    | '/imoveis/$slug'
    | '/meio-ambiente/areas'
    | '/meio-ambiente/fauna'
    | '/meio-ambiente/lazer'
    | '/bairros/'
    | '/blog/'
    | '/condominios/'
    | '/guia/'
    | '/imoveis/'
    | '/meio-ambiente/'
    | '/_authenticated/audit/$id'
    | '/_authenticated/cms/$id'
    | '/_authenticated/cms/'
    | '/api/public/editorial-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlphavilleRoute: typeof AlphavilleRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  EmpresasRoute: typeof EmpresasRoute
  EscolasRoute: typeof EscolasRoute
  GuiaRoute: typeof GuiaRouteWithChildren
  GuiaAlphavilleRoute: typeof GuiaAlphavilleRoute
  GuiaBarueriRoute: typeof GuiaBarueriRoute
  GuiaSantanaDeParnaibaRoute: typeof GuiaSantanaDeParnaibaRoute
  GuiaTamboreRoute: typeof GuiaTamboreRoute
  HistoriaRoute: typeof HistoriaRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
  InvestimentosRoute: typeof InvestimentosRoute
  MeioAmbienteRoute: typeof MeioAmbienteRouteWithChildren
  MercadoImobiliarioRoute: typeof MercadoImobiliarioRoute
  RestaurantesRoute: typeof RestaurantesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ArtigosSlugRoute: typeof ArtigosSlugRoute
  BairrosSlugRoute: typeof BairrosSlugRoute
  CondominiosSlugRoute: typeof CondominiosSlugRoute
  BairrosIndexRoute: typeof BairrosIndexRoute
  CondominiosIndexRoute: typeof CondominiosIndexRoute
  ApiPublicEditorialImageSplatRoute: typeof ApiPublicEditorialImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado-imobiliario': {
      id: '/mercado-imobiliario'
      path: '/mercado-imobiliario'
      fullPath: '/mercado-imobiliario'
      preLoaderRoute: typeof MercadoImobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meio-ambiente': {
      id: '/meio-ambiente'
      path: '/meio-ambiente'
      fullPath: '/meio-ambiente'
      preLoaderRoute: typeof MeioAmbienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-tambore': {
      id: '/guia-tambore'
      path: '/guia-tambore'
      fullPath: '/guia-tambore'
      preLoaderRoute: typeof GuiaTamboreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-santana-de-parnaiba': {
      id: '/guia-santana-de-parnaiba'
      path: '/guia-santana-de-parnaiba'
      fullPath: '/guia-santana-de-parnaiba'
      preLoaderRoute: typeof GuiaSantanaDeParnaibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-barueri': {
      id: '/guia-barueri'
      path: '/guia-barueri'
      fullPath: '/guia-barueri'
      preLoaderRoute: typeof GuiaBarueriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-alphaville': {
      id: '/guia-alphaville'
      path: '/guia-alphaville'
      fullPath: '/guia-alphaville'
      preLoaderRoute: typeof GuiaAlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphaville': {
      id: '/alphaville'
      path: '/alphaville'
      fullPath: '/alphaville'
      preLoaderRoute: typeof AlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meio-ambiente/': {
      id: '/meio-ambiente/'
      path: '/'
      fullPath: '/meio-ambiente/'
      preLoaderRoute: typeof MeioAmbienteIndexRouteImport
      parentRoute: typeof MeioAmbienteRoute
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/guia/': {
      id: '/guia/'
      path: '/'
      fullPath: '/guia/'
      preLoaderRoute: typeof GuiaIndexRouteImport
      parentRoute: typeof GuiaRoute
    }
    '/condominios/': {
      id: '/condominios/'
      path: '/condominios'
      fullPath: '/condominios/'
      preLoaderRoute: typeof CondominiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bairros/': {
      id: '/bairros/'
      path: '/bairros'
      fullPath: '/bairros/'
      preLoaderRoute: typeof BairrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meio-ambiente/lazer': {
      id: '/meio-ambiente/lazer'
      path: '/lazer'
      fullPath: '/meio-ambiente/lazer'
      preLoaderRoute: typeof MeioAmbienteLazerRouteImport
      parentRoute: typeof MeioAmbienteRoute
    }
    '/meio-ambiente/fauna': {
      id: '/meio-ambiente/fauna'
      path: '/fauna'
      fullPath: '/meio-ambiente/fauna'
      preLoaderRoute: typeof MeioAmbienteFaunaRouteImport
      parentRoute: typeof MeioAmbienteRoute
    }
    '/meio-ambiente/areas': {
      id: '/meio-ambiente/areas'
      path: '/areas'
      fullPath: '/meio-ambiente/areas'
      preLoaderRoute: typeof MeioAmbienteAreasRouteImport
      parentRoute: typeof MeioAmbienteRoute
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/guia/$slug': {
      id: '/guia/$slug'
      path: '/$slug'
      fullPath: '/guia/$slug'
      preLoaderRoute: typeof GuiaSlugRouteImport
      parentRoute: typeof GuiaRoute
    }
    '/condominios/$slug': {
      id: '/condominios/$slug'
      path: '/condominios/$slug'
      fullPath: '/condominios/$slug'
      preLoaderRoute: typeof CondominiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bairros/$slug': {
      id: '/bairros/$slug'
      path: '/bairros/$slug'
      fullPath: '/bairros/$slug'
      preLoaderRoute: typeof BairrosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$slug': {
      id: '/artigos/$slug'
      path: '/artigos/$slug'
      fullPath: '/artigos/$slug'
      preLoaderRoute: typeof ArtigosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/': {
      id: '/_authenticated/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof AuthenticatedCmsIndexRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/$id': {
      id: '/_authenticated/cms/$id'
      path: '/$id'
      fullPath: '/cms/$id'
      preLoaderRoute: typeof AuthenticatedCmsIdRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/audit/$id': {
      id: '/_authenticated/audit/$id'
      path: '/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuthenticatedAuditIdRouteImport
      parentRoute: typeof AuthenticatedAuditRoute
    }
    '/api/public/editorial-image/$': {
      id: '/api/public/editorial-image/$'
      path: '/api/public/editorial-image/$'
      fullPath: '/api/public/editorial-image/$'
      preLoaderRoute: typeof ApiPublicEditorialImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAuditRouteChildren {
  AuthenticatedAuditIdRoute: typeof AuthenticatedAuditIdRoute
}

const AuthenticatedAuditRouteChildren: AuthenticatedAuditRouteChildren = {
  AuthenticatedAuditIdRoute: AuthenticatedAuditIdRoute,
}

const AuthenticatedAuditRouteWithChildren =
  AuthenticatedAuditRoute._addFileChildren(AuthenticatedAuditRouteChildren)

interface AuthenticatedCmsRouteChildren {
  AuthenticatedCmsIdRoute: typeof AuthenticatedCmsIdRoute
  AuthenticatedCmsIndexRoute: typeof AuthenticatedCmsIndexRoute
}

const AuthenticatedCmsRouteChildren: AuthenticatedCmsRouteChildren = {
  AuthenticatedCmsIdRoute: AuthenticatedCmsIdRoute,
  AuthenticatedCmsIndexRoute: AuthenticatedCmsIndexRoute,
}

const AuthenticatedCmsRouteWithChildren =
  AuthenticatedCmsRoute._addFileChildren(AuthenticatedCmsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRouteWithChildren
  AuthenticatedCmsRoute: typeof AuthenticatedCmsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRouteWithChildren,
  AuthenticatedCmsRoute: AuthenticatedCmsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GuiaRouteChildren {
  GuiaSlugRoute: typeof GuiaSlugRoute
  GuiaIndexRoute: typeof GuiaIndexRoute
}

const GuiaRouteChildren: GuiaRouteChildren = {
  GuiaSlugRoute: GuiaSlugRoute,
  GuiaIndexRoute: GuiaIndexRoute,
}

const GuiaRouteWithChildren = GuiaRoute._addFileChildren(GuiaRouteChildren)

interface ImoveisRouteChildren {
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisSlugRoute: ImoveisSlugRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

interface MeioAmbienteRouteChildren {
  MeioAmbienteAreasRoute: typeof MeioAmbienteAreasRoute
  MeioAmbienteFaunaRoute: typeof MeioAmbienteFaunaRoute
  MeioAmbienteLazerRoute: typeof MeioAmbienteLazerRoute
  MeioAmbienteIndexRoute: typeof MeioAmbienteIndexRoute
}

const MeioAmbienteRouteChildren: MeioAmbienteRouteChildren = {
  MeioAmbienteAreasRoute: MeioAmbienteAreasRoute,
  MeioAmbienteFaunaRoute: MeioAmbienteFaunaRoute,
  MeioAmbienteLazerRoute: MeioAmbienteLazerRoute,
  MeioAmbienteIndexRoute: MeioAmbienteIndexRoute,
}

const MeioAmbienteRouteWithChildren = MeioAmbienteRoute._addFileChildren(
  MeioAmbienteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlphavilleRoute: AlphavilleRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  EmpresasRoute: EmpresasRoute,
  EscolasRoute: EscolasRoute,
  GuiaRoute: GuiaRouteWithChildren,
  GuiaAlphavilleRoute: GuiaAlphavilleRoute,
  GuiaBarueriRoute: GuiaBarueriRoute,
  GuiaSantanaDeParnaibaRoute: GuiaSantanaDeParnaibaRoute,
  GuiaTamboreRoute: GuiaTamboreRoute,
  HistoriaRoute: HistoriaRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
  InvestimentosRoute: InvestimentosRoute,
  MeioAmbienteRoute: MeioAmbienteRouteWithChildren,
  MercadoImobiliarioRoute: MercadoImobiliarioRoute,
  RestaurantesRoute: RestaurantesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ArtigosSlugRoute: ArtigosSlugRoute,
  BairrosSlugRoute: BairrosSlugRoute,
  CondominiosSlugRoute: CondominiosSlugRoute,
  BairrosIndexRoute: BairrosIndexRoute,
  CondominiosIndexRoute: CondominiosIndexRoute,
  ApiPublicEditorialImageSplatRoute: ApiPublicEditorialImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
