/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as MercadoImobiliarioRouteImport } from './routes/mercado-imobiliario'
import { Route as MeioAmbienteRouteImport } from './routes/meio-ambiente'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GuiaTamboreRouteImport } from './routes/guia-tambore'
import { Route as GuiaSantanaDeParnaibaRouteImport } from './routes/guia-santana-de-parnaiba'
import { Route as GuiaBarueriRouteImport } from './routes/guia-barueri'
import { Route as GuiaAlphavilleRouteImport } from './routes/guia-alphaville'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as CondominiosRouteImport } from './routes/condominios'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BairrosRouteImport } from './routes/bairros'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlphavilleRouteImport } from './routes/alphaville'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'
import { Route as CondominiosSlugRouteImport } from './routes/condominios.$slug'
import { Route as CondominioSlugRouteImport } from './routes/condominio.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BairrosSlugRouteImport } from './routes/bairros.$slug'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAuditIdRouteImport } from './routes/_authenticated/audit.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoImobiliarioRoute = MercadoImobiliarioRouteImport.update({
  id: '/mercado-imobiliario',
  path: '/mercado-imobiliario',
  getParentRoute: () => rootRouteImport,
} as any)
const MeioAmbienteRoute = MeioAmbienteRouteImport.update({
  id: '/meio-ambiente',
  path: '/meio-ambiente',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaTamboreRoute = GuiaTamboreRouteImport.update({
  id: '/guia-tambore',
  path: '/guia-tambore',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaSantanaDeParnaibaRoute = GuiaSantanaDeParnaibaRouteImport.update({
  id: '/guia-santana-de-parnaiba',
  path: '/guia-santana-de-parnaiba',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaBarueriRoute = GuiaBarueriRouteImport.update({
  id: '/guia-barueri',
  path: '/guia-barueri',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaAlphavilleRoute = GuiaAlphavilleRouteImport.update({
  id: '/guia-alphaville',
  path: '/guia-alphaville',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosRoute = CondominiosRouteImport.update({
  id: '/condominios',
  path: '/condominios',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BairrosRoute = BairrosRouteImport.update({
  id: '/bairros',
  path: '/bairros',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphavilleRoute = AlphavilleRouteImport.update({
  id: '/alphaville',
  path: '/alphaville',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImoveisRoute,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ImoveisRoute,
} as any)
const CondominiosSlugRoute = CondominiosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CondominiosRoute,
} as any)
const CondominioSlugRoute = CondominioSlugRouteImport.update({
  id: '/condominio/$slug',
  path: '/condominio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BairrosSlugRoute = BairrosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BairrosRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditIdRoute = AuthenticatedAuditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAuditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alphaville': typeof AlphavilleRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/condominios': typeof CondominiosRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/investimentos': typeof InvestimentosRoute
  '/meio-ambiente': typeof MeioAmbienteRoute
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominio/$slug': typeof CondominioSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alphaville': typeof AlphavilleRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/condominios': typeof CondominiosRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/investimentos': typeof InvestimentosRoute
  '/meio-ambiente': typeof MeioAmbienteRoute
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominio/$slug': typeof CondominioSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alphaville': typeof AlphavilleRoute
  '/auth': typeof AuthRoute
  '/bairros': typeof BairrosRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/condominios': typeof CondominiosRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/investimentos': typeof InvestimentosRoute
  '/meio-ambiente': typeof MeioAmbienteRoute
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/restaurantes': typeof RestaurantesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRouteWithChildren
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominio/$slug': typeof CondominioSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/_authenticated/audit/$id': typeof AuthenticatedAuditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alphaville'
    | '/auth'
    | '/bairros'
    | '/blog'
    | '/condominios'
    | '/empresas'
    | '/escolas'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/imoveis'
    | '/investimentos'
    | '/meio-ambiente'
    | '/mercado-imobiliario'
    | '/restaurantes'
    | '/sitemap.xml'
    | '/admin'
    | '/audit'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominio/$slug'
    | '/condominios/$slug'
    | '/imoveis/$slug'
    | '/imoveis/'
    | '/audit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alphaville'
    | '/auth'
    | '/bairros'
    | '/blog'
    | '/condominios'
    | '/empresas'
    | '/escolas'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/investimentos'
    | '/meio-ambiente'
    | '/mercado-imobiliario'
    | '/restaurantes'
    | '/sitemap.xml'
    | '/admin'
    | '/audit'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominio/$slug'
    | '/condominios/$slug'
    | '/imoveis/$slug'
    | '/imoveis'
    | '/audit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alphaville'
    | '/auth'
    | '/bairros'
    | '/blog'
    | '/condominios'
    | '/empresas'
    | '/escolas'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/imoveis'
    | '/investimentos'
    | '/meio-ambiente'
    | '/mercado-imobiliario'
    | '/restaurantes'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/audit'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominio/$slug'
    | '/condominios/$slug'
    | '/imoveis/$slug'
    | '/imoveis/'
    | '/_authenticated/audit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlphavilleRoute: typeof AlphavilleRoute
  AuthRoute: typeof AuthRoute
  BairrosRoute: typeof BairrosRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CondominiosRoute: typeof CondominiosRouteWithChildren
  EmpresasRoute: typeof EmpresasRoute
  EscolasRoute: typeof EscolasRoute
  GuiaAlphavilleRoute: typeof GuiaAlphavilleRoute
  GuiaBarueriRoute: typeof GuiaBarueriRoute
  GuiaSantanaDeParnaibaRoute: typeof GuiaSantanaDeParnaibaRoute
  GuiaTamboreRoute: typeof GuiaTamboreRoute
  HistoriaRoute: typeof HistoriaRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
  InvestimentosRoute: typeof InvestimentosRoute
  MeioAmbienteRoute: typeof MeioAmbienteRoute
  MercadoImobiliarioRoute: typeof MercadoImobiliarioRoute
  RestaurantesRoute: typeof RestaurantesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CondominioSlugRoute: typeof CondominioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado-imobiliario': {
      id: '/mercado-imobiliario'
      path: '/mercado-imobiliario'
      fullPath: '/mercado-imobiliario'
      preLoaderRoute: typeof MercadoImobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meio-ambiente': {
      id: '/meio-ambiente'
      path: '/meio-ambiente'
      fullPath: '/meio-ambiente'
      preLoaderRoute: typeof MeioAmbienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-tambore': {
      id: '/guia-tambore'
      path: '/guia-tambore'
      fullPath: '/guia-tambore'
      preLoaderRoute: typeof GuiaTamboreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-santana-de-parnaiba': {
      id: '/guia-santana-de-parnaiba'
      path: '/guia-santana-de-parnaiba'
      fullPath: '/guia-santana-de-parnaiba'
      preLoaderRoute: typeof GuiaSantanaDeParnaibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-barueri': {
      id: '/guia-barueri'
      path: '/guia-barueri'
      fullPath: '/guia-barueri'
      preLoaderRoute: typeof GuiaBarueriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-alphaville': {
      id: '/guia-alphaville'
      path: '/guia-alphaville'
      fullPath: '/guia-alphaville'
      preLoaderRoute: typeof GuiaAlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios': {
      id: '/condominios'
      path: '/condominios'
      fullPath: '/condominios'
      preLoaderRoute: typeof CondominiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bairros': {
      id: '/bairros'
      path: '/bairros'
      fullPath: '/bairros'
      preLoaderRoute: typeof BairrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphaville': {
      id: '/alphaville'
      path: '/alphaville'
      fullPath: '/alphaville'
      preLoaderRoute: typeof AlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/condominios/$slug': {
      id: '/condominios/$slug'
      path: '/$slug'
      fullPath: '/condominios/$slug'
      preLoaderRoute: typeof CondominiosSlugRouteImport
      parentRoute: typeof CondominiosRoute
    }
    '/condominio/$slug': {
      id: '/condominio/$slug'
      path: '/condominio/$slug'
      fullPath: '/condominio/$slug'
      preLoaderRoute: typeof CondominioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bairros/$slug': {
      id: '/bairros/$slug'
      path: '/$slug'
      fullPath: '/bairros/$slug'
      preLoaderRoute: typeof BairrosSlugRouteImport
      parentRoute: typeof BairrosRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/$id': {
      id: '/_authenticated/audit/$id'
      path: '/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuthenticatedAuditIdRouteImport
      parentRoute: typeof AuthenticatedAuditRoute
    }
  }
}

interface AuthenticatedAuditRouteChildren {
  AuthenticatedAuditIdRoute: typeof AuthenticatedAuditIdRoute
}

const AuthenticatedAuditRouteChildren: AuthenticatedAuditRouteChildren = {
  AuthenticatedAuditIdRoute: AuthenticatedAuditIdRoute,
}

const AuthenticatedAuditRouteWithChildren =
  AuthenticatedAuditRoute._addFileChildren(AuthenticatedAuditRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BairrosRouteChildren {
  BairrosSlugRoute: typeof BairrosSlugRoute
}

const BairrosRouteChildren: BairrosRouteChildren = {
  BairrosSlugRoute: BairrosSlugRoute,
}

const BairrosRouteWithChildren =
  BairrosRoute._addFileChildren(BairrosRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CondominiosRouteChildren {
  CondominiosSlugRoute: typeof CondominiosSlugRoute
}

const CondominiosRouteChildren: CondominiosRouteChildren = {
  CondominiosSlugRoute: CondominiosSlugRoute,
}

const CondominiosRouteWithChildren = CondominiosRoute._addFileChildren(
  CondominiosRouteChildren,
)

interface ImoveisRouteChildren {
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisSlugRoute: ImoveisSlugRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlphavilleRoute: AlphavilleRoute,
  AuthRoute: AuthRoute,
  BairrosRoute: BairrosRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CondominiosRoute: CondominiosRouteWithChildren,
  EmpresasRoute: EmpresasRoute,
  EscolasRoute: EscolasRoute,
  GuiaAlphavilleRoute: GuiaAlphavilleRoute,
  GuiaBarueriRoute: GuiaBarueriRoute,
  GuiaSantanaDeParnaibaRoute: GuiaSantanaDeParnaibaRoute,
  GuiaTamboreRoute: GuiaTamboreRoute,
  HistoriaRoute: HistoriaRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
  InvestimentosRoute: InvestimentosRoute,
  MeioAmbienteRoute: MeioAmbienteRoute,
  MercadoImobiliarioRoute: MercadoImobiliarioRoute,
  RestaurantesRoute: RestaurantesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CondominioSlugRoute: CondominioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
