/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as RuasRouteImport } from './routes/ruas'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PoliticaDeAtendimentoRouteImport } from './routes/politica-de-atendimento'
import { Route as PerguntasFrequentesRouteImport } from './routes/perguntas-frequentes'
import { Route as MercadoImobiliarioRouteImport } from './routes/mercado-imobiliario'
import { Route as MeioAmbienteRouteImport } from './routes/meio-ambiente'
import { Route as MapaDoSiteRouteImport } from './routes/mapa-do-site'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GuiaTamboreRouteImport } from './routes/guia-tambore'
import { Route as GuiaSantanaDeParnaibaRouteImport } from './routes/guia-santana-de-parnaiba'
import { Route as GuiaDeRuasAlphavilleRouteImport } from './routes/guia-de-ruas-alphaville'
import { Route as GuiaBarueriRouteImport } from './routes/guia-barueri'
import { Route as GuiaAlphavilleRouteImport } from './routes/guia-alphaville'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as EscolasRouteImport } from './routes/escolas'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoTrabalhamosRouteImport } from './routes/como-trabalhamos'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'
import { Route as AlphavilleRouteImport } from './routes/alphaville'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RuasIndexRouteImport } from './routes/ruas.index'
import { Route as MeioAmbienteIndexRouteImport } from './routes/meio-ambiente.index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as GuiaIndexRouteImport } from './routes/guia.index'
import { Route as GuiaDeRuasAlphavilleIndexRouteImport } from './routes/guia-de-ruas-alphaville.index'
import { Route as CondominiosIndexRouteImport } from './routes/condominios.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BairrosIndexRouteImport } from './routes/bairros.index'
import { Route as RuasSlugRouteImport } from './routes/ruas.$slug'
import { Route as ParceirosMpdRouteImport } from './routes/parceiros.mpd'
import { Route as MeioAmbienteLazerRouteImport } from './routes/meio-ambiente.lazer'
import { Route as MeioAmbienteFaunaRouteImport } from './routes/meio-ambiente.fauna'
import { Route as MeioAmbienteAreasRouteImport } from './routes/meio-ambiente.areas'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'
import { Route as GuiaSlugRouteImport } from './routes/guia.$slug'
import { Route as GuiaDeRuasAlphavilleSlugRouteImport } from './routes/guia-de-ruas-alphaville.$slug'
import { Route as EmpreendimentosTerrahAlphavilleRouteImport } from './routes/empreendimentos.terrah-alphaville'
import { Route as EmpreendimentosFloraAlphavilleRouteImport } from './routes/empreendimentos.flora-alphaville'
import { Route as EmpreendimentosAndromedaByMpdRouteImport } from './routes/empreendimentos.andromeda-by-mpd'
import { Route as EmpreendimentosSlugRouteImport } from './routes/empreendimentos.$slug'
import { Route as CondominiosSlugRouteImport } from './routes/condominios.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BairrosSlugRouteImport } from './routes/bairros.$slug'
import { Route as ArtigosSlugRouteImport } from './routes/artigos.$slug'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin-seo'
import { Route as AuthenticatedAdminRuasRouteImport } from './routes/_authenticated/admin-ruas'
import { Route as AuthenticatedAdminRadarRouteImport } from './routes/_authenticated/admin-radar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCmsIndexRouteImport } from './routes/_authenticated/cms.index'
import { Route as ApiPublicIndexnowKeyDottxtRouteImport } from './routes/api/public/indexnow-key[.]txt'
import { Route as AuthenticatedCmsIdRouteImport } from './routes/_authenticated/cms.$id'
import { Route as AuthenticatedAuditIdRouteImport } from './routes/_authenticated/audit.$id'
import { Route as AuthenticatedAdminRuasRelatoriosRouteImport } from './routes/_authenticated/admin-ruas.relatorios'
import { Route as AuthenticatedAdminRuasIdRouteImport } from './routes/_authenticated/admin-ruas.$id'
import { Route as ApiPublicHooksSeoMonthlyRefreshRouteImport } from './routes/api/public/hooks/seo-monthly-refresh'
import { Route as ApiPublicEditorialImageSplatRouteImport } from './routes/api/public/editorial-image.$'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RuasRoute = RuasRouteImport.update({
  id: '/ruas',
  path: '/ruas',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeAtendimentoRoute = PoliticaDeAtendimentoRouteImport.update({
  id: '/politica-de-atendimento',
  path: '/politica-de-atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntasFrequentesRoute = PerguntasFrequentesRouteImport.update({
  id: '/perguntas-frequentes',
  path: '/perguntas-frequentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoImobiliarioRoute = MercadoImobiliarioRouteImport.update({
  id: '/mercado-imobiliario',
  path: '/mercado-imobiliario',
  getParentRoute: () => rootRouteImport,
} as any)
const MeioAmbienteRoute = MeioAmbienteRouteImport.update({
  id: '/meio-ambiente',
  path: '/meio-ambiente',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaDoSiteRoute = MapaDoSiteRouteImport.update({
  id: '/mapa-do-site',
  path: '/mapa-do-site',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaTamboreRoute = GuiaTamboreRouteImport.update({
  id: '/guia-tambore',
  path: '/guia-tambore',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaSantanaDeParnaibaRoute = GuiaSantanaDeParnaibaRouteImport.update({
  id: '/guia-santana-de-parnaiba',
  path: '/guia-santana-de-parnaiba',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDeRuasAlphavilleRoute = GuiaDeRuasAlphavilleRouteImport.update({
  id: '/guia-de-ruas-alphaville',
  path: '/guia-de-ruas-alphaville',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaBarueriRoute = GuiaBarueriRouteImport.update({
  id: '/guia-barueri',
  path: '/guia-barueri',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaAlphavilleRoute = GuiaAlphavilleRouteImport.update({
  id: '/guia-alphaville',
  path: '/guia-alphaville',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolasRoute = EscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoTrabalhamosRoute = ComoTrabalhamosRouteImport.update({
  id: '/como-trabalhamos',
  path: '/como-trabalhamos',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AlphavilleRoute = AlphavilleRouteImport.update({
  id: '/alphaville',
  path: '/alphaville',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuasIndexRoute = RuasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RuasRoute,
} as any)
const MeioAmbienteIndexRoute = MeioAmbienteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeioAmbienteRoute,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImoveisRoute,
} as any)
const GuiaIndexRoute = GuiaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuiaRoute,
} as any)
const GuiaDeRuasAlphavilleIndexRoute =
  GuiaDeRuasAlphavilleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => GuiaDeRuasAlphavilleRoute,
  } as any)
const CondominiosIndexRoute = CondominiosIndexRouteImport.update({
  id: '/condominios/',
  path: '/condominios/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BairrosIndexRoute = BairrosIndexRouteImport.update({
  id: '/bairros/',
  path: '/bairros/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuasSlugRoute = RuasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RuasRoute,
} as any)
const ParceirosMpdRoute = ParceirosMpdRouteImport.update({
  id: '/parceiros/mpd',
  path: '/parceiros/mpd',
  getParentRoute: () => rootRouteImport,
} as any)
const MeioAmbienteLazerRoute = MeioAmbienteLazerRouteImport.update({
  id: '/lazer',
  path: '/lazer',
  getParentRoute: () => MeioAmbienteRoute,
} as any)
const MeioAmbienteFaunaRoute = MeioAmbienteFaunaRouteImport.update({
  id: '/fauna',
  path: '/fauna',
  getParentRoute: () => MeioAmbienteRoute,
} as any)
const MeioAmbienteAreasRoute = MeioAmbienteAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => MeioAmbienteRoute,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ImoveisRoute,
} as any)
const GuiaSlugRoute = GuiaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuiaRoute,
} as any)
const GuiaDeRuasAlphavilleSlugRoute =
  GuiaDeRuasAlphavilleSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => GuiaDeRuasAlphavilleRoute,
  } as any)
const EmpreendimentosTerrahAlphavilleRoute =
  EmpreendimentosTerrahAlphavilleRouteImport.update({
    id: '/empreendimentos/terrah-alphaville',
    path: '/empreendimentos/terrah-alphaville',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmpreendimentosFloraAlphavilleRoute =
  EmpreendimentosFloraAlphavilleRouteImport.update({
    id: '/empreendimentos/flora-alphaville',
    path: '/empreendimentos/flora-alphaville',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmpreendimentosAndromedaByMpdRoute =
  EmpreendimentosAndromedaByMpdRouteImport.update({
    id: '/empreendimentos/andromeda-by-mpd',
    path: '/empreendimentos/andromeda-by-mpd',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmpreendimentosSlugRoute = EmpreendimentosSlugRouteImport.update({
  id: '/empreendimentos/$slug',
  path: '/empreendimentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CondominiosSlugRoute = CondominiosSlugRouteImport.update({
  id: '/condominios/$slug',
  path: '/condominios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BairrosSlugRoute = BairrosSlugRouteImport.update({
  id: '/bairros/$slug',
  path: '/bairros/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosSlugRoute = ArtigosSlugRouteImport.update({
  id: '/artigos/$slug',
  path: '/artigos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/admin-seo',
  path: '/admin-seo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRuasRoute = AuthenticatedAdminRuasRouteImport.update({
  id: '/admin-ruas',
  path: '/admin-ruas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRadarRoute = AuthenticatedAdminRadarRouteImport.update({
  id: '/admin-radar',
  path: '/admin-radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCmsIndexRoute = AuthenticatedCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const ApiPublicIndexnowKeyDottxtRoute =
  ApiPublicIndexnowKeyDottxtRouteImport.update({
    id: '/api/public/indexnow-key.txt',
    path: '/api/public/indexnow-key.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCmsIdRoute = AuthenticatedCmsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedAuditIdRoute = AuthenticatedAuditIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAuditRoute,
} as any)
const AuthenticatedAdminRuasRelatoriosRoute =
  AuthenticatedAdminRuasRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAdminRuasRoute,
  } as any)
const AuthenticatedAdminRuasIdRoute =
  AuthenticatedAdminRuasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminRuasRoute,
  } as any)
const ApiPublicHooksSeoMonthlyRefreshRoute =
  ApiPublicHooksSeoMonthlyRefreshRouteImport.update({
    id: '/api/public/hooks/seo-monthly-refresh',
    path: '/api/public/hooks/seo-monthly-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEditorialImageSplatRoute =
  ApiPublicEditorialImageSplatRouteImport.update({
    id: '/api/public/editorial-image/$',
    path: '/api/public/editorial-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alphaville': typeof AlphavilleRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia': typeof GuiaRouteWithChildren
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-de-ruas-alphaville': typeof GuiaDeRuasAlphavilleRouteWithChildren
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/investimentos': typeof InvestimentosRoute
  '/lgpd': typeof LgpdRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/meio-ambiente': typeof MeioAmbienteRouteWithChildren
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-atendimento': typeof PoliticaDeAtendimentoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/restaurantes': typeof RestaurantesRoute
  '/ruas': typeof RuasRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/transparencia': typeof TransparenciaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-radar': typeof AuthenticatedAdminRadarRoute
  '/admin-ruas': typeof AuthenticatedAdminRuasRouteWithChildren
  '/admin-seo': typeof AuthenticatedAdminSeoRoute
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/cms': typeof AuthenticatedCmsRouteWithChildren
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/empreendimentos/$slug': typeof EmpreendimentosSlugRoute
  '/empreendimentos/andromeda-by-mpd': typeof EmpreendimentosAndromedaByMpdRoute
  '/empreendimentos/flora-alphaville': typeof EmpreendimentosFloraAlphavilleRoute
  '/empreendimentos/terrah-alphaville': typeof EmpreendimentosTerrahAlphavilleRoute
  '/guia-de-ruas-alphaville/$slug': typeof GuiaDeRuasAlphavilleSlugRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/meio-ambiente/areas': typeof MeioAmbienteAreasRoute
  '/meio-ambiente/fauna': typeof MeioAmbienteFaunaRoute
  '/meio-ambiente/lazer': typeof MeioAmbienteLazerRoute
  '/parceiros/mpd': typeof ParceirosMpdRoute
  '/ruas/$slug': typeof RuasSlugRoute
  '/bairros/': typeof BairrosIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/condominios/': typeof CondominiosIndexRoute
  '/guia-de-ruas-alphaville/': typeof GuiaDeRuasAlphavilleIndexRoute
  '/guia/': typeof GuiaIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/meio-ambiente/': typeof MeioAmbienteIndexRoute
  '/ruas/': typeof RuasIndexRoute
  '/admin-ruas/$id': typeof AuthenticatedAdminRuasIdRoute
  '/admin-ruas/relatorios': typeof AuthenticatedAdminRuasRelatoriosRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
  '/cms/$id': typeof AuthenticatedCmsIdRoute
  '/api/public/indexnow-key.txt': typeof ApiPublicIndexnowKeyDottxtRoute
  '/cms/': typeof AuthenticatedCmsIndexRoute
  '/api/public/editorial-image/$': typeof ApiPublicEditorialImageSplatRoute
  '/api/public/hooks/seo-monthly-refresh': typeof ApiPublicHooksSeoMonthlyRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alphaville': typeof AlphavilleRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/investimentos': typeof InvestimentosRoute
  '/lgpd': typeof LgpdRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-atendimento': typeof PoliticaDeAtendimentoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/restaurantes': typeof RestaurantesRoute
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/transparencia': typeof TransparenciaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-radar': typeof AuthenticatedAdminRadarRoute
  '/admin-ruas': typeof AuthenticatedAdminRuasRouteWithChildren
  '/admin-seo': typeof AuthenticatedAdminSeoRoute
  '/audit': typeof AuthenticatedAuditRouteWithChildren
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/empreendimentos/$slug': typeof EmpreendimentosSlugRoute
  '/empreendimentos/andromeda-by-mpd': typeof EmpreendimentosAndromedaByMpdRoute
  '/empreendimentos/flora-alphaville': typeof EmpreendimentosFloraAlphavilleRoute
  '/empreendimentos/terrah-alphaville': typeof EmpreendimentosTerrahAlphavilleRoute
  '/guia-de-ruas-alphaville/$slug': typeof GuiaDeRuasAlphavilleSlugRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/meio-ambiente/areas': typeof MeioAmbienteAreasRoute
  '/meio-ambiente/fauna': typeof MeioAmbienteFaunaRoute
  '/meio-ambiente/lazer': typeof MeioAmbienteLazerRoute
  '/parceiros/mpd': typeof ParceirosMpdRoute
  '/ruas/$slug': typeof RuasSlugRoute
  '/bairros': typeof BairrosIndexRoute
  '/blog': typeof BlogIndexRoute
  '/condominios': typeof CondominiosIndexRoute
  '/guia-de-ruas-alphaville': typeof GuiaDeRuasAlphavilleIndexRoute
  '/guia': typeof GuiaIndexRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/meio-ambiente': typeof MeioAmbienteIndexRoute
  '/ruas': typeof RuasIndexRoute
  '/admin-ruas/$id': typeof AuthenticatedAdminRuasIdRoute
  '/admin-ruas/relatorios': typeof AuthenticatedAdminRuasRelatoriosRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
  '/cms/$id': typeof AuthenticatedCmsIdRoute
  '/api/public/indexnow-key.txt': typeof ApiPublicIndexnowKeyDottxtRoute
  '/cms': typeof AuthenticatedCmsIndexRoute
  '/api/public/editorial-image/$': typeof ApiPublicEditorialImageSplatRoute
  '/api/public/hooks/seo-monthly-refresh': typeof ApiPublicHooksSeoMonthlyRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/alphaville': typeof AlphavilleRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/como-trabalhamos': typeof ComoTrabalhamosRoute
  '/contato': typeof ContatoRoute
  '/empresas': typeof EmpresasRoute
  '/escolas': typeof EscolasRoute
  '/guia': typeof GuiaRouteWithChildren
  '/guia-alphaville': typeof GuiaAlphavilleRoute
  '/guia-barueri': typeof GuiaBarueriRoute
  '/guia-de-ruas-alphaville': typeof GuiaDeRuasAlphavilleRouteWithChildren
  '/guia-santana-de-parnaiba': typeof GuiaSantanaDeParnaibaRoute
  '/guia-tambore': typeof GuiaTamboreRoute
  '/historia': typeof HistoriaRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/investimentos': typeof InvestimentosRoute
  '/lgpd': typeof LgpdRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/meio-ambiente': typeof MeioAmbienteRouteWithChildren
  '/mercado-imobiliario': typeof MercadoImobiliarioRoute
  '/perguntas-frequentes': typeof PerguntasFrequentesRoute
  '/politica-de-atendimento': typeof PoliticaDeAtendimentoRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/quem-somos': typeof QuemSomosRoute
  '/restaurantes': typeof RestaurantesRoute
  '/ruas': typeof RuasRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/transparencia': typeof TransparenciaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-radar': typeof AuthenticatedAdminRadarRoute
  '/_authenticated/admin-ruas': typeof AuthenticatedAdminRuasRouteWithChildren
  '/_authenticated/admin-seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRouteWithChildren
  '/_authenticated/cms': typeof AuthenticatedCmsRouteWithChildren
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/bairros/$slug': typeof BairrosSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/condominios/$slug': typeof CondominiosSlugRoute
  '/empreendimentos/$slug': typeof EmpreendimentosSlugRoute
  '/empreendimentos/andromeda-by-mpd': typeof EmpreendimentosAndromedaByMpdRoute
  '/empreendimentos/flora-alphaville': typeof EmpreendimentosFloraAlphavilleRoute
  '/empreendimentos/terrah-alphaville': typeof EmpreendimentosTerrahAlphavilleRoute
  '/guia-de-ruas-alphaville/$slug': typeof GuiaDeRuasAlphavilleSlugRoute
  '/guia/$slug': typeof GuiaSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/meio-ambiente/areas': typeof MeioAmbienteAreasRoute
  '/meio-ambiente/fauna': typeof MeioAmbienteFaunaRoute
  '/meio-ambiente/lazer': typeof MeioAmbienteLazerRoute
  '/parceiros/mpd': typeof ParceirosMpdRoute
  '/ruas/$slug': typeof RuasSlugRoute
  '/bairros/': typeof BairrosIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/condominios/': typeof CondominiosIndexRoute
  '/guia-de-ruas-alphaville/': typeof GuiaDeRuasAlphavilleIndexRoute
  '/guia/': typeof GuiaIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/meio-ambiente/': typeof MeioAmbienteIndexRoute
  '/ruas/': typeof RuasIndexRoute
  '/_authenticated/admin-ruas/$id': typeof AuthenticatedAdminRuasIdRoute
  '/_authenticated/admin-ruas/relatorios': typeof AuthenticatedAdminRuasRelatoriosRoute
  '/_authenticated/audit/$id': typeof AuthenticatedAuditIdRoute
  '/_authenticated/cms/$id': typeof AuthenticatedCmsIdRoute
  '/api/public/indexnow-key.txt': typeof ApiPublicIndexnowKeyDottxtRoute
  '/_authenticated/cms/': typeof AuthenticatedCmsIndexRoute
  '/api/public/editorial-image/$': typeof ApiPublicEditorialImageSplatRoute
  '/api/public/hooks/seo-monthly-refresh': typeof ApiPublicHooksSeoMonthlyRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alphaville'
    | '/areas-de-atuacao'
    | '/auth'
    | '/aviso-legal'
    | '/blog'
    | '/como-trabalhamos'
    | '/contato'
    | '/empresas'
    | '/escolas'
    | '/guia'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-de-ruas-alphaville'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/imoveis'
    | '/investimentos'
    | '/lgpd'
    | '/mapa-do-site'
    | '/meio-ambiente'
    | '/mercado-imobiliario'
    | '/perguntas-frequentes'
    | '/politica-de-atendimento'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/restaurantes'
    | '/ruas'
    | '/servicos'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/transparencia'
    | '/admin'
    | '/admin-radar'
    | '/admin-ruas'
    | '/admin-seo'
    | '/audit'
    | '/cms'
    | '/artigos/$slug'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominios/$slug'
    | '/empreendimentos/$slug'
    | '/empreendimentos/andromeda-by-mpd'
    | '/empreendimentos/flora-alphaville'
    | '/empreendimentos/terrah-alphaville'
    | '/guia-de-ruas-alphaville/$slug'
    | '/guia/$slug'
    | '/imoveis/$slug'
    | '/meio-ambiente/areas'
    | '/meio-ambiente/fauna'
    | '/meio-ambiente/lazer'
    | '/parceiros/mpd'
    | '/ruas/$slug'
    | '/bairros/'
    | '/blog/'
    | '/condominios/'
    | '/guia-de-ruas-alphaville/'
    | '/guia/'
    | '/imoveis/'
    | '/meio-ambiente/'
    | '/ruas/'
    | '/admin-ruas/$id'
    | '/admin-ruas/relatorios'
    | '/audit/$id'
    | '/cms/$id'
    | '/api/public/indexnow-key.txt'
    | '/cms/'
    | '/api/public/editorial-image/$'
    | '/api/public/hooks/seo-monthly-refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alphaville'
    | '/areas-de-atuacao'
    | '/auth'
    | '/aviso-legal'
    | '/como-trabalhamos'
    | '/contato'
    | '/empresas'
    | '/escolas'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/investimentos'
    | '/lgpd'
    | '/mapa-do-site'
    | '/mercado-imobiliario'
    | '/perguntas-frequentes'
    | '/politica-de-atendimento'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/restaurantes'
    | '/servicos'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/transparencia'
    | '/admin'
    | '/admin-radar'
    | '/admin-ruas'
    | '/admin-seo'
    | '/audit'
    | '/artigos/$slug'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominios/$slug'
    | '/empreendimentos/$slug'
    | '/empreendimentos/andromeda-by-mpd'
    | '/empreendimentos/flora-alphaville'
    | '/empreendimentos/terrah-alphaville'
    | '/guia-de-ruas-alphaville/$slug'
    | '/guia/$slug'
    | '/imoveis/$slug'
    | '/meio-ambiente/areas'
    | '/meio-ambiente/fauna'
    | '/meio-ambiente/lazer'
    | '/parceiros/mpd'
    | '/ruas/$slug'
    | '/bairros'
    | '/blog'
    | '/condominios'
    | '/guia-de-ruas-alphaville'
    | '/guia'
    | '/imoveis'
    | '/meio-ambiente'
    | '/ruas'
    | '/admin-ruas/$id'
    | '/admin-ruas/relatorios'
    | '/audit/$id'
    | '/cms/$id'
    | '/api/public/indexnow-key.txt'
    | '/cms'
    | '/api/public/editorial-image/$'
    | '/api/public/hooks/seo-monthly-refresh'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alphaville'
    | '/areas-de-atuacao'
    | '/auth'
    | '/aviso-legal'
    | '/blog'
    | '/como-trabalhamos'
    | '/contato'
    | '/empresas'
    | '/escolas'
    | '/guia'
    | '/guia-alphaville'
    | '/guia-barueri'
    | '/guia-de-ruas-alphaville'
    | '/guia-santana-de-parnaiba'
    | '/guia-tambore'
    | '/historia'
    | '/imoveis'
    | '/investimentos'
    | '/lgpd'
    | '/mapa-do-site'
    | '/meio-ambiente'
    | '/mercado-imobiliario'
    | '/perguntas-frequentes'
    | '/politica-de-atendimento'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/quem-somos'
    | '/restaurantes'
    | '/ruas'
    | '/servicos'
    | '/sitemap.xml'
    | '/termos-de-uso'
    | '/transparencia'
    | '/_authenticated/admin'
    | '/_authenticated/admin-radar'
    | '/_authenticated/admin-ruas'
    | '/_authenticated/admin-seo'
    | '/_authenticated/audit'
    | '/_authenticated/cms'
    | '/artigos/$slug'
    | '/bairros/$slug'
    | '/blog/$slug'
    | '/condominios/$slug'
    | '/empreendimentos/$slug'
    | '/empreendimentos/andromeda-by-mpd'
    | '/empreendimentos/flora-alphaville'
    | '/empreendimentos/terrah-alphaville'
    | '/guia-de-ruas-alphaville/$slug'
    | '/guia/$slug'
    | '/imoveis/$slug'
    | '/meio-ambiente/areas'
    | '/meio-ambiente/fauna'
    | '/meio-ambiente/lazer'
    | '/parceiros/mpd'
    | '/ruas/$slug'
    | '/bairros/'
    | '/blog/'
    | '/condominios/'
    | '/guia-de-ruas-alphaville/'
    | '/guia/'
    | '/imoveis/'
    | '/meio-ambiente/'
    | '/ruas/'
    | '/_authenticated/admin-ruas/$id'
    | '/_authenticated/admin-ruas/relatorios'
    | '/_authenticated/audit/$id'
    | '/_authenticated/cms/$id'
    | '/api/public/indexnow-key.txt'
    | '/_authenticated/cms/'
    | '/api/public/editorial-image/$'
    | '/api/public/hooks/seo-monthly-refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AlphavilleRoute: typeof AlphavilleRoute
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRoute
  AuthRoute: typeof AuthRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BlogRoute: typeof BlogRouteWithChildren
  ComoTrabalhamosRoute: typeof ComoTrabalhamosRoute
  ContatoRoute: typeof ContatoRoute
  EmpresasRoute: typeof EmpresasRoute
  EscolasRoute: typeof EscolasRoute
  GuiaRoute: typeof GuiaRouteWithChildren
  GuiaAlphavilleRoute: typeof GuiaAlphavilleRoute
  GuiaBarueriRoute: typeof GuiaBarueriRoute
  GuiaDeRuasAlphavilleRoute: typeof GuiaDeRuasAlphavilleRouteWithChildren
  GuiaSantanaDeParnaibaRoute: typeof GuiaSantanaDeParnaibaRoute
  GuiaTamboreRoute: typeof GuiaTamboreRoute
  HistoriaRoute: typeof HistoriaRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
  InvestimentosRoute: typeof InvestimentosRoute
  LgpdRoute: typeof LgpdRoute
  MapaDoSiteRoute: typeof MapaDoSiteRoute
  MeioAmbienteRoute: typeof MeioAmbienteRouteWithChildren
  MercadoImobiliarioRoute: typeof MercadoImobiliarioRoute
  PerguntasFrequentesRoute: typeof PerguntasFrequentesRoute
  PoliticaDeAtendimentoRoute: typeof PoliticaDeAtendimentoRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  QuemSomosRoute: typeof QuemSomosRoute
  RestaurantesRoute: typeof RestaurantesRoute
  RuasRoute: typeof RuasRouteWithChildren
  ServicosRoute: typeof ServicosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TransparenciaRoute: typeof TransparenciaRoute
  ArtigosSlugRoute: typeof ArtigosSlugRoute
  BairrosSlugRoute: typeof BairrosSlugRoute
  CondominiosSlugRoute: typeof CondominiosSlugRoute
  EmpreendimentosSlugRoute: typeof EmpreendimentosSlugRoute
  EmpreendimentosAndromedaByMpdRoute: typeof EmpreendimentosAndromedaByMpdRoute
  EmpreendimentosFloraAlphavilleRoute: typeof EmpreendimentosFloraAlphavilleRoute
  EmpreendimentosTerrahAlphavilleRoute: typeof EmpreendimentosTerrahAlphavilleRoute
  ParceirosMpdRoute: typeof ParceirosMpdRoute
  BairrosIndexRoute: typeof BairrosIndexRoute
  CondominiosIndexRoute: typeof CondominiosIndexRoute
  ApiPublicIndexnowKeyDottxtRoute: typeof ApiPublicIndexnowKeyDottxtRoute
  ApiPublicEditorialImageSplatRoute: typeof ApiPublicEditorialImageSplatRoute
  ApiPublicHooksSeoMonthlyRefreshRoute: typeof ApiPublicHooksSeoMonthlyRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruas': {
      id: '/ruas'
      path: '/ruas'
      fullPath: '/ruas'
      preLoaderRoute: typeof RuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-atendimento': {
      id: '/politica-de-atendimento'
      path: '/politica-de-atendimento'
      fullPath: '/politica-de-atendimento'
      preLoaderRoute: typeof PoliticaDeAtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntas-frequentes': {
      id: '/perguntas-frequentes'
      path: '/perguntas-frequentes'
      fullPath: '/perguntas-frequentes'
      preLoaderRoute: typeof PerguntasFrequentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado-imobiliario': {
      id: '/mercado-imobiliario'
      path: '/mercado-imobiliario'
      fullPath: '/mercado-imobiliario'
      preLoaderRoute: typeof MercadoImobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meio-ambiente': {
      id: '/meio-ambiente'
      path: '/meio-ambiente'
      fullPath: '/meio-ambiente'
      preLoaderRoute: typeof MeioAmbienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-do-site': {
      id: '/mapa-do-site'
      path: '/mapa-do-site'
      fullPath: '/mapa-do-site'
      preLoaderRoute: typeof MapaDoSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-tambore': {
      id: '/guia-tambore'
      path: '/guia-tambore'
      fullPath: '/guia-tambore'
      preLoaderRoute: typeof GuiaTamboreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-santana-de-parnaiba': {
      id: '/guia-santana-de-parnaiba'
      path: '/guia-santana-de-parnaiba'
      fullPath: '/guia-santana-de-parnaiba'
      preLoaderRoute: typeof GuiaSantanaDeParnaibaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-de-ruas-alphaville': {
      id: '/guia-de-ruas-alphaville'
      path: '/guia-de-ruas-alphaville'
      fullPath: '/guia-de-ruas-alphaville'
      preLoaderRoute: typeof GuiaDeRuasAlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-barueri': {
      id: '/guia-barueri'
      path: '/guia-barueri'
      fullPath: '/guia-barueri'
      preLoaderRoute: typeof GuiaBarueriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-alphaville': {
      id: '/guia-alphaville'
      path: '/guia-alphaville'
      fullPath: '/guia-alphaville'
      preLoaderRoute: typeof GuiaAlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolas': {
      id: '/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof EscolasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-trabalhamos': {
      id: '/como-trabalhamos'
      path: '/como-trabalhamos'
      fullPath: '/como-trabalhamos'
      preLoaderRoute: typeof ComoTrabalhamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alphaville': {
      id: '/alphaville'
      path: '/alphaville'
      fullPath: '/alphaville'
      preLoaderRoute: typeof AlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruas/': {
      id: '/ruas/'
      path: '/'
      fullPath: '/ruas/'
      preLoaderRoute: typeof RuasIndexRouteImport
      parentRoute: typeof RuasRoute
    }
    '/meio-ambiente/': {
      id: '/meio-ambiente/'
      path: '/'
      fullPath: '/meio-ambiente/'
      preLoaderRoute: typeof MeioAmbienteIndexRouteImport
      parentRoute: typeof MeioAmbienteRoute
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/guia/': {
      id: '/guia/'
      path: '/'
      fullPath: '/guia/'
      preLoaderRoute: typeof GuiaIndexRouteImport
      parentRoute: typeof GuiaRoute
    }
    '/guia-de-ruas-alphaville/': {
      id: '/guia-de-ruas-alphaville/'
      path: '/'
      fullPath: '/guia-de-ruas-alphaville/'
      preLoaderRoute: typeof GuiaDeRuasAlphavilleIndexRouteImport
      parentRoute: typeof GuiaDeRuasAlphavilleRoute
    }
    '/condominios/': {
      id: '/condominios/'
      path: '/condominios'
      fullPath: '/condominios/'
      preLoaderRoute: typeof CondominiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bairros/': {
      id: '/bairros/'
      path: '/bairros'
      fullPath: '/bairros/'
      preLoaderRoute: typeof BairrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ruas/$slug': {
      id: '/ruas/$slug'
      path: '/$slug'
      fullPath: '/ruas/$slug'
      preLoaderRoute: typeof RuasSlugRouteImport
      parentRoute: typeof RuasRoute
    }
    '/parceiros/mpd': {
      id: '/parceiros/mpd'
      path: '/parceiros/mpd'
      fullPath: '/parceiros/mpd'
      preLoaderRoute: typeof ParceirosMpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meio-ambiente/lazer': {
      id: '/meio-ambiente/lazer'
      path: '/lazer'
      fullPath: '/meio-ambiente/lazer'
      preLoaderRoute: typeof MeioAmbienteLazerRouteImport
      parentRoute: typeof MeioAmbienteRoute
    }
    '/meio-ambiente/fauna': {
      id: '/meio-ambiente/fauna'
      path: '/fauna'
      fullPath: '/meio-ambiente/fauna'
      preLoaderRoute: typeof MeioAmbienteFaunaRouteImport
      parentRoute: typeof MeioAmbienteRoute
    }
    '/meio-ambiente/areas': {
      id: '/meio-ambiente/areas'
      path: '/areas'
      fullPath: '/meio-ambiente/areas'
      preLoaderRoute: typeof MeioAmbienteAreasRouteImport
      parentRoute: typeof MeioAmbienteRoute
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/guia/$slug': {
      id: '/guia/$slug'
      path: '/$slug'
      fullPath: '/guia/$slug'
      preLoaderRoute: typeof GuiaSlugRouteImport
      parentRoute: typeof GuiaRoute
    }
    '/guia-de-ruas-alphaville/$slug': {
      id: '/guia-de-ruas-alphaville/$slug'
      path: '/$slug'
      fullPath: '/guia-de-ruas-alphaville/$slug'
      preLoaderRoute: typeof GuiaDeRuasAlphavilleSlugRouteImport
      parentRoute: typeof GuiaDeRuasAlphavilleRoute
    }
    '/empreendimentos/terrah-alphaville': {
      id: '/empreendimentos/terrah-alphaville'
      path: '/empreendimentos/terrah-alphaville'
      fullPath: '/empreendimentos/terrah-alphaville'
      preLoaderRoute: typeof EmpreendimentosTerrahAlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/flora-alphaville': {
      id: '/empreendimentos/flora-alphaville'
      path: '/empreendimentos/flora-alphaville'
      fullPath: '/empreendimentos/flora-alphaville'
      preLoaderRoute: typeof EmpreendimentosFloraAlphavilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/andromeda-by-mpd': {
      id: '/empreendimentos/andromeda-by-mpd'
      path: '/empreendimentos/andromeda-by-mpd'
      fullPath: '/empreendimentos/andromeda-by-mpd'
      preLoaderRoute: typeof EmpreendimentosAndromedaByMpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/$slug': {
      id: '/empreendimentos/$slug'
      path: '/empreendimentos/$slug'
      fullPath: '/empreendimentos/$slug'
      preLoaderRoute: typeof EmpreendimentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condominios/$slug': {
      id: '/condominios/$slug'
      path: '/condominios/$slug'
      fullPath: '/condominios/$slug'
      preLoaderRoute: typeof CondominiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bairros/$slug': {
      id: '/bairros/$slug'
      path: '/bairros/$slug'
      fullPath: '/bairros/$slug'
      preLoaderRoute: typeof BairrosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$slug': {
      id: '/artigos/$slug'
      path: '/artigos/$slug'
      fullPath: '/artigos/$slug'
      preLoaderRoute: typeof ArtigosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-seo': {
      id: '/_authenticated/admin-seo'
      path: '/admin-seo'
      fullPath: '/admin-seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-ruas': {
      id: '/_authenticated/admin-ruas'
      path: '/admin-ruas'
      fullPath: '/admin-ruas'
      preLoaderRoute: typeof AuthenticatedAdminRuasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-radar': {
      id: '/_authenticated/admin-radar'
      path: '/admin-radar'
      fullPath: '/admin-radar'
      preLoaderRoute: typeof AuthenticatedAdminRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cms/': {
      id: '/_authenticated/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof AuthenticatedCmsIndexRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/api/public/indexnow-key.txt': {
      id: '/api/public/indexnow-key.txt'
      path: '/api/public/indexnow-key.txt'
      fullPath: '/api/public/indexnow-key.txt'
      preLoaderRoute: typeof ApiPublicIndexnowKeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cms/$id': {
      id: '/_authenticated/cms/$id'
      path: '/$id'
      fullPath: '/cms/$id'
      preLoaderRoute: typeof AuthenticatedCmsIdRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/audit/$id': {
      id: '/_authenticated/audit/$id'
      path: '/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuthenticatedAuditIdRouteImport
      parentRoute: typeof AuthenticatedAuditRoute
    }
    '/_authenticated/admin-ruas/relatorios': {
      id: '/_authenticated/admin-ruas/relatorios'
      path: '/relatorios'
      fullPath: '/admin-ruas/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRuasRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAdminRuasRoute
    }
    '/_authenticated/admin-ruas/$id': {
      id: '/_authenticated/admin-ruas/$id'
      path: '/$id'
      fullPath: '/admin-ruas/$id'
      preLoaderRoute: typeof AuthenticatedAdminRuasIdRouteImport
      parentRoute: typeof AuthenticatedAdminRuasRoute
    }
    '/api/public/hooks/seo-monthly-refresh': {
      id: '/api/public/hooks/seo-monthly-refresh'
      path: '/api/public/hooks/seo-monthly-refresh'
      fullPath: '/api/public/hooks/seo-monthly-refresh'
      preLoaderRoute: typeof ApiPublicHooksSeoMonthlyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/editorial-image/$': {
      id: '/api/public/editorial-image/$'
      path: '/api/public/editorial-image/$'
      fullPath: '/api/public/editorial-image/$'
      preLoaderRoute: typeof ApiPublicEditorialImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRuasRouteChildren {
  AuthenticatedAdminRuasIdRoute: typeof AuthenticatedAdminRuasIdRoute
  AuthenticatedAdminRuasRelatoriosRoute: typeof AuthenticatedAdminRuasRelatoriosRoute
}

const AuthenticatedAdminRuasRouteChildren: AuthenticatedAdminRuasRouteChildren =
  {
    AuthenticatedAdminRuasIdRoute: AuthenticatedAdminRuasIdRoute,
    AuthenticatedAdminRuasRelatoriosRoute:
      AuthenticatedAdminRuasRelatoriosRoute,
  }

const AuthenticatedAdminRuasRouteWithChildren =
  AuthenticatedAdminRuasRoute._addFileChildren(
    AuthenticatedAdminRuasRouteChildren,
  )

interface AuthenticatedAuditRouteChildren {
  AuthenticatedAuditIdRoute: typeof AuthenticatedAuditIdRoute
}

const AuthenticatedAuditRouteChildren: AuthenticatedAuditRouteChildren = {
  AuthenticatedAuditIdRoute: AuthenticatedAuditIdRoute,
}

const AuthenticatedAuditRouteWithChildren =
  AuthenticatedAuditRoute._addFileChildren(AuthenticatedAuditRouteChildren)

interface AuthenticatedCmsRouteChildren {
  AuthenticatedCmsIdRoute: typeof AuthenticatedCmsIdRoute
  AuthenticatedCmsIndexRoute: typeof AuthenticatedCmsIndexRoute
}

const AuthenticatedCmsRouteChildren: AuthenticatedCmsRouteChildren = {
  AuthenticatedCmsIdRoute: AuthenticatedCmsIdRoute,
  AuthenticatedCmsIndexRoute: AuthenticatedCmsIndexRoute,
}

const AuthenticatedCmsRouteWithChildren =
  AuthenticatedCmsRoute._addFileChildren(AuthenticatedCmsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminRadarRoute: typeof AuthenticatedAdminRadarRoute
  AuthenticatedAdminRuasRoute: typeof AuthenticatedAdminRuasRouteWithChildren
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRouteWithChildren
  AuthenticatedCmsRoute: typeof AuthenticatedCmsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminRadarRoute: AuthenticatedAdminRadarRoute,
  AuthenticatedAdminRuasRoute: AuthenticatedAdminRuasRouteWithChildren,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRouteWithChildren,
  AuthenticatedCmsRoute: AuthenticatedCmsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GuiaRouteChildren {
  GuiaSlugRoute: typeof GuiaSlugRoute
  GuiaIndexRoute: typeof GuiaIndexRoute
}

const GuiaRouteChildren: GuiaRouteChildren = {
  GuiaSlugRoute: GuiaSlugRoute,
  GuiaIndexRoute: GuiaIndexRoute,
}

const GuiaRouteWithChildren = GuiaRoute._addFileChildren(GuiaRouteChildren)

interface GuiaDeRuasAlphavilleRouteChildren {
  GuiaDeRuasAlphavilleSlugRoute: typeof GuiaDeRuasAlphavilleSlugRoute
  GuiaDeRuasAlphavilleIndexRoute: typeof GuiaDeRuasAlphavilleIndexRoute
}

const GuiaDeRuasAlphavilleRouteChildren: GuiaDeRuasAlphavilleRouteChildren = {
  GuiaDeRuasAlphavilleSlugRoute: GuiaDeRuasAlphavilleSlugRoute,
  GuiaDeRuasAlphavilleIndexRoute: GuiaDeRuasAlphavilleIndexRoute,
}

const GuiaDeRuasAlphavilleRouteWithChildren =
  GuiaDeRuasAlphavilleRoute._addFileChildren(GuiaDeRuasAlphavilleRouteChildren)

interface ImoveisRouteChildren {
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisSlugRoute: ImoveisSlugRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

interface MeioAmbienteRouteChildren {
  MeioAmbienteAreasRoute: typeof MeioAmbienteAreasRoute
  MeioAmbienteFaunaRoute: typeof MeioAmbienteFaunaRoute
  MeioAmbienteLazerRoute: typeof MeioAmbienteLazerRoute
  MeioAmbienteIndexRoute: typeof MeioAmbienteIndexRoute
}

const MeioAmbienteRouteChildren: MeioAmbienteRouteChildren = {
  MeioAmbienteAreasRoute: MeioAmbienteAreasRoute,
  MeioAmbienteFaunaRoute: MeioAmbienteFaunaRoute,
  MeioAmbienteLazerRoute: MeioAmbienteLazerRoute,
  MeioAmbienteIndexRoute: MeioAmbienteIndexRoute,
}

const MeioAmbienteRouteWithChildren = MeioAmbienteRoute._addFileChildren(
  MeioAmbienteRouteChildren,
)

interface RuasRouteChildren {
  RuasSlugRoute: typeof RuasSlugRoute
  RuasIndexRoute: typeof RuasIndexRoute
}

const RuasRouteChildren: RuasRouteChildren = {
  RuasSlugRoute: RuasSlugRoute,
  RuasIndexRoute: RuasIndexRoute,
}

const RuasRouteWithChildren = RuasRoute._addFileChildren(RuasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AlphavilleRoute: AlphavilleRoute,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRoute,
  AuthRoute: AuthRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BlogRoute: BlogRouteWithChildren,
  ComoTrabalhamosRoute: ComoTrabalhamosRoute,
  ContatoRoute: ContatoRoute,
  EmpresasRoute: EmpresasRoute,
  EscolasRoute: EscolasRoute,
  GuiaRoute: GuiaRouteWithChildren,
  GuiaAlphavilleRoute: GuiaAlphavilleRoute,
  GuiaBarueriRoute: GuiaBarueriRoute,
  GuiaDeRuasAlphavilleRoute: GuiaDeRuasAlphavilleRouteWithChildren,
  GuiaSantanaDeParnaibaRoute: GuiaSantanaDeParnaibaRoute,
  GuiaTamboreRoute: GuiaTamboreRoute,
  HistoriaRoute: HistoriaRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
  InvestimentosRoute: InvestimentosRoute,
  LgpdRoute: LgpdRoute,
  MapaDoSiteRoute: MapaDoSiteRoute,
  MeioAmbienteRoute: MeioAmbienteRouteWithChildren,
  MercadoImobiliarioRoute: MercadoImobiliarioRoute,
  PerguntasFrequentesRoute: PerguntasFrequentesRoute,
  PoliticaDeAtendimentoRoute: PoliticaDeAtendimentoRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  QuemSomosRoute: QuemSomosRoute,
  RestaurantesRoute: RestaurantesRoute,
  RuasRoute: RuasRouteWithChildren,
  ServicosRoute: ServicosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TransparenciaRoute: TransparenciaRoute,
  ArtigosSlugRoute: ArtigosSlugRoute,
  BairrosSlugRoute: BairrosSlugRoute,
  CondominiosSlugRoute: CondominiosSlugRoute,
  EmpreendimentosSlugRoute: EmpreendimentosSlugRoute,
  EmpreendimentosAndromedaByMpdRoute: EmpreendimentosAndromedaByMpdRoute,
  EmpreendimentosFloraAlphavilleRoute: EmpreendimentosFloraAlphavilleRoute,
  EmpreendimentosTerrahAlphavilleRoute: EmpreendimentosTerrahAlphavilleRoute,
  ParceirosMpdRoute: ParceirosMpdRoute,
  BairrosIndexRoute: BairrosIndexRoute,
  CondominiosIndexRoute: CondominiosIndexRoute,
  ApiPublicIndexnowKeyDottxtRoute: ApiPublicIndexnowKeyDottxtRoute,
  ApiPublicEditorialImageSplatRoute: ApiPublicEditorialImageSplatRoute,
  ApiPublicHooksSeoMonthlyRefreshRoute: ApiPublicHooksSeoMonthlyRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
