ALTER TABLE public.editorial_pages
  ADD COLUMN IF NOT EXISTS help_title text,
  ADD COLUMN IF NOT EXISTS help_text text,
  ADD COLUMN IF NOT EXISTS help_button_label text,
  ADD COLUMN IF NOT EXISTS help_button_url text,
  ADD COLUMN IF NOT EXISTS cta_title text,
  ADD COLUMN IF NOT EXISTS cta_text text,
  ADD COLUMN IF NOT EXISTS cta_button_label text,
  ADD COLUMN IF NOT EXISTS cta_button_url text,
  ADD COLUMN IF NOT EXISTS cidade text,
  ADD COLUMN IF NOT EXISTS regiao text,
  ADD COLUMN IF NOT EXISTS bairro text,
  ADD COLUMN IF NOT EXISTS condominio text,
  ADD COLUMN IF NOT EXISTS categoria_editorial text,
  ADD COLUMN IF NOT EXISTS perfil_publico text,
  ADD COLUMN IF NOT EXISTS intencao_imobiliaria text,
  ADD COLUMN IF NOT EXISTS tipos_imovel_relacionados text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS tags_contextuais text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS conversion_context text,
  ADD COLUMN IF NOT EXISTS personalization_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS reading_minutes integer,
  ADD COLUMN IF NOT EXISTS faq jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS related_post_ids uuid[] NOT NULL DEFAULT '{}';